# Pipeline for gitlab.com (silver account)

# Use image stored in local gitlab repo
image: registry.gitlab.com/osp-silver/panorama_gem/jruby_with_chrome:9.2.11.1

stages:
- build
- test
- deploy

before_script:
  - cat /etc/*-release
  - ruby -v
  - which ruby


prepare_env:
  stage: build
  script:
    - bundle install