# create secrets for encryption

secrets_file = File.join(Rails.root, 'config', 'secrets.yml')
rails_env = ENV['RAILS_ENV'] || 'production'
content = "
# File generated by config/initializers/create_secrets.rb

#{rails_env}:
    secret_key_base: \"#{EnvHelper.secret_key_base}\"
"
begin
  File.write(secrets_file, content)
rescue Exception => e
  puts "Error creating secrets file '#{secrets_file}'\n#{e.class}: #{e.message}"
end

