# GitHub action recipe
# preconditions:
#   - Install Java
#     > wget https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm
#     > rpm -Uvh jdk-17_linux-x64_bin.rpm && rm jdk-17_linux-x64_bin.rpm
#   - Install Chromium for the dependencies needed by playwright:
#   - Install jRuby
#     > curl -sSL https://get.rvm.io | bash
#     > source "$HOME/.rvm/scripts/rvm"
#     > rvm install ${JRUBY_VERSION}
#     > rvm --default use ${JRUBY_VERSION}
#     > gem install bundler

name: Panorama_Gem CI

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string, runs on Sunday morning
    - cron: '0 0 * * 0'

jobs:
  test_11_2_0_4-ee:     { uses: "rammpeter/panorama_gem/.github/workflows/run_tests.yml@master", with: { db_version: "11.2.0.4-ee", container: "PDB" }, secrets: "inherit"}
  test_12_1_0_2-ee:     { uses: "rammpeter/panorama_gem/.github/workflows/run_tests.yml@master", with: { db_version: "12.1.0.2-ee", container: "PDB" }, secrets: "inherit"}
  test_12_2_0_1-ee_PDB: { uses: "rammpeter/panorama_gem/.github/workflows/run_tests.yml@master", with: { db_version: "12.2.0.1-ee", container: "PDB" }, secrets: "inherit"}
  test_12_2_0_1-ee_CDB: { uses: "rammpeter/panorama_gem/.github/workflows/run_tests.yml@master", with: { db_version: "12.2.0.1-ee", container: "CDB" }, secrets: "inherit"}


#        - 18.3.0.0-ee
#        - 18.4.0.0-xe
#        - 19.3.0.0-ee
#        - 19.10.0.0-ee
#        - 19.10.0.0-se2
#        - autonomous
